{% set name = "markitdown" %}
{% set version = "0.0.2" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/markitdown-{{ version }}.tar.gz
  sha256: 678fc2c9bc4eded0941c01155251982cab1f86c8148c8ac7ca3869116d3d49d7

build:
  entry_points:
    - markitdown = markitdown.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - azure-ai-documentintelligence
    - azure-identity
    - beautifulsoup4
    - charset-normalizer
    - mammoth
    - markdownify
    - numpy
    - olefile
    - openai
    - openpyxl
    - pandas
    - pathvalidate
    - pdfminer.six
    - pdfminer-six
    - puremagic
    - python-pptx
    - python >={{ python_min }}
    - pydub
    - requests
    - speechrecognition
    - xlrd
    - youtube-transcript-api

test:
  imports:
    - markitdown
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/microsoft/markitdown
  summary: Python tool for converting files and office documents to Markdown.
  dev_url: https://github.com/microsoft/markitdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johnhany97
    - sarthakpati
