{% set name = "markitdown" %}
{% set version = "0.1.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/markitdown-{{ version }}.tar.gz
  sha256: da97a55a45a3d775ea758e88a344d5cac94ee97115fb0293f99027d32c2fc3f6

build:
  entry_points:
    - markitdown = markitdown.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - beautifulsoup4
    - requests
    - markdownify
    - magika >=0.6.1,<0.7.dev0
    - charset-normalizer

test:
  imports:
    - markitdown
  commands:
    - pip check
    - markitdown --help
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: Utility tool for converting various files to Markdown
  dev_url: https://github.com/microsoft/markitdown
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - johnhany97
    - sarthakpati
