schema_version: 1

context:
  name: markitdown
  version: "0.1.3"
  python_min: '3.10'
  python_max: '4.0'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/markitdown-${{ version }}.tar.gz
  sha256: b0d9127c3373a68274dede6af6c9bb0684b78ce364c727c4c304da97a20d6fd9

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check
  python:
    entry_points:
      - markitdown = markitdown.__main__:main

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }},<${{ python_max }}
    - azure-ai-documentintelligence
    - azure-identity
    - beautifulsoup4
    - charset-normalizer
    - defusedxml
    - lxml
    - markdownify
    - magika >=0.6.1,<0.7.dev0
    - mammoth >=1.10.0
    - olefile
    - openpyxl
    - onnxruntime <=1.20.1
    - pandas
    - pdfminer.six
    - pydub
    - python-pptx
    - requests
    - SpeechRecognition
    - xlrd
    - youtube-transcript-api >=1.0.0

tests:
  - python:
      imports:
        - markitdown
      pip_check: true
      python_version:
        - ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - markitdown --help

about:
  summary: Utility tool for converting various files to Markdown
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/microsoft/markitdown
  description: |
    Python tool for converting files and office documents to Markdown.
  repository: https://github.com/microsoft/markitdown

extra:
  recipe-maintainers:
    - johnhany97
    - sarthakpati
